version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: foodgram-frontend
    image: drsova/frontend_foodgram
    volumes:
      - static:/static
    command: cp -r /app/build/. /app/static/

  backend:
    container_name: foodgram-backend
    image: drsova/backend_foodgram
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - frontend
      - db

  nginx:
    container_name: foodgram-gateway
    image: drsova/gateway_foodgram
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9090:80